export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const IS_LOADING = 'IS_LOADING'
export const HAS_ERROR = 'HAS_ERROR'

export const IS_OPENED_MODAL = 'IS_OPENED_MODAL'
export const GET_ID_ITEM = 'GET_ID_ITEM'

export const ADD_BUN = 'ADD_BUN'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const SORT_CONSTRUCTOR = 'SORT_CONSTRUCTOR'
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR'

export const GET_ORDER = 'GET_ORDER'
export const IS_OPENED_ORDER_MODAL = 'IS_OPENED_ORDER_MODAL'
export const IS_LOADING_ORDER = 'IS_LOADING_ORDER'
export const HAS_ERROR_ORDER = 'HAS_ERROR_ORDER'
